name: dart_datastore_example
version: 0.0.1
authors:
- Adam Singer <financeCoding@gmail.com>
description: A sample command-line application for dart and google datastore
homepage: https://github.com/financeCoding/dart_datastore_example
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  google_oauth2_client: '>=0.3.6 <0.3.7'
  google_datastore_v1beta2_api: ">=0.4.0 <0.5.0"
